### ISSUE TITLE
Bluetooth SPP + BLE Server

### ISSUE THREAD

**Issue by vicatcu** [beegee-tokyo/ESP32-Weatherstation#3]
I followed the reasoning in https://desire.giesecke.tk/index.php/2018/02/27/esp32-bluetooth-serial-and-ble-server-running-together/ just this evening and I tried connecting to the ESP32 using the nRF UART Android app as well as the Serial Bluetooth Terminal Android app. It failed with in both cases with similar messages indicating that no Serial Profile was found. Have you tried this recently (i.e. with the 1.0.4 Boards Manager release of arduino-esp32?

**Comment by beegee-tokyo** [comment]
I didn't use that code since a long time (as you can see, last updated 2 years ago). 
Since BLE offers now a BLE Serial service, I am using that one and have everything on BLE rather than running BLE and BT Serial together. Easier to handle.
